# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relays.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Controller(object):
    def setupUi(self, Controller):
        Controller.setObjectName("Controller")
        Controller.resize(596, 699)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        Controller.setFont(font)
        Controller.setAutoFillBackground(False)
        self.PiPlatesRelays = QtWidgets.QGroupBox(Controller)
        self.PiPlatesRelays.setGeometry(QtCore.QRect(10, 10, 571, 341))
        self.PiPlatesRelays.setObjectName("PiPlatesRelays")
        self.pb_relay_8 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_8.setGeometry(QtCore.QRect(10, 40, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_8.setFont(font)
        self.pb_relay_8.setCheckable(True)
        self.pb_relay_8.setObjectName("pb_relay_8")
        self.pb_relay_7 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_7.setGeometry(QtCore.QRect(490, 120, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_7.setFont(font)
        self.pb_relay_7.setCheckable(True)
        self.pb_relay_7.setObjectName("pb_relay_7")
        self.pb_relay_13 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_13.setGeometry(QtCore.QRect(410, 40, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_13.setFont(font)
        self.pb_relay_13.setCheckable(True)
        self.pb_relay_13.setObjectName("pb_relay_13")
        self.pb_relay_6 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_6.setGeometry(QtCore.QRect(410, 120, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_6.setFont(font)
        self.pb_relay_6.setCheckable(True)
        self.pb_relay_6.setObjectName("pb_relay_6")
        self.pb_relay_9 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_9.setGeometry(QtCore.QRect(90, 40, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_9.setFont(font)
        self.pb_relay_9.setCheckable(True)
        self.pb_relay_9.setObjectName("pb_relay_9")
        self.pb_relay_5 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_5.setGeometry(QtCore.QRect(330, 120, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_5.setFont(font)
        self.pb_relay_5.setCheckable(True)
        self.pb_relay_5.setObjectName("pb_relay_5")
        self.pb_relay_12 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_12.setGeometry(QtCore.QRect(330, 40, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_12.setFont(font)
        self.pb_relay_12.setCheckable(True)
        self.pb_relay_12.setObjectName("pb_relay_12")
        self.pb_relay_1 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_1.setGeometry(QtCore.QRect(10, 120, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_1.setFont(font)
        self.pb_relay_1.setCheckable(True)
        self.pb_relay_1.setObjectName("pb_relay_1")
        self.pb_relay_14 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_14.setGeometry(QtCore.QRect(490, 40, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_14.setFont(font)
        self.pb_relay_14.setCheckable(True)
        self.pb_relay_14.setObjectName("pb_relay_14")
        self.pb_relay_2 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_2.setGeometry(QtCore.QRect(90, 120, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_2.setFont(font)
        self.pb_relay_2.setCheckable(True)
        self.pb_relay_2.setObjectName("pb_relay_2")
        self.pb_relay_4 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_4.setGeometry(QtCore.QRect(250, 120, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_4.setFont(font)
        self.pb_relay_4.setCheckable(True)
        self.pb_relay_4.setObjectName("pb_relay_4")
        self.pb_relay_11 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_11.setGeometry(QtCore.QRect(250, 40, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_11.setFont(font)
        self.pb_relay_11.setCheckable(True)
        self.pb_relay_11.setObjectName("pb_relay_11")
        self.pb_relay_3 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_3.setGeometry(QtCore.QRect(170, 120, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_3.setFont(font)
        self.pb_relay_3.setCheckable(True)
        self.pb_relay_3.setObjectName("pb_relay_3")
        self.pb_relay_10 = QtWidgets.QPushButton(self.PiPlatesRelays)
        self.pb_relay_10.setGeometry(QtCore.QRect(170, 40, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_10.setFont(font)
        self.pb_relay_10.setCheckable(True)
        self.pb_relay_10.setObjectName("pb_relay_10")
        self.PiPlatesGlobal = QtWidgets.QGroupBox(self.PiPlatesRelays)
        self.PiPlatesGlobal.setGeometry(QtCore.QRect(10, 210, 181, 121))
        self.PiPlatesGlobal.setObjectName("PiPlatesGlobal")
        self.pb_relay_all_on = QtWidgets.QPushButton(self.PiPlatesGlobal)
        self.pb_relay_all_on.setGeometry(QtCore.QRect(10, 30, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_all_on.setFont(font)
        self.pb_relay_all_on.setCheckable(True)
        self.pb_relay_all_on.setAutoExclusive(True)
        self.pb_relay_all_on.setObjectName("pb_relay_all_on")
        self.pb_relay_all_off = QtWidgets.QPushButton(self.PiPlatesGlobal)
        self.pb_relay_all_off.setGeometry(QtCore.QRect(90, 30, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_relay_all_off.setFont(font)
        self.pb_relay_all_off.setCheckable(True)
        self.pb_relay_all_off.setAutoExclusive(True)
        self.pb_relay_all_off.setObjectName("pb_relay_all_off")
        self.TB6600 = QtWidgets.QGroupBox(Controller)
        self.TB6600.setGeometry(QtCore.QRect(10, 370, 571, 121))
        self.TB6600.setObjectName("TB6600")
        self.pb_tb6600_test = QtWidgets.QPushButton(self.TB6600)
        self.pb_tb6600_test.setGeometry(QtCore.QRect(10, 30, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_tb6600_test.setFont(font)
        self.pb_tb6600_test.setCheckable(True)
        self.pb_tb6600_test.setObjectName("pb_tb6600_test")
        self.pb_tb6600_move_cw = QtWidgets.QPushButton(self.TB6600)
        self.pb_tb6600_move_cw.setGeometry(QtCore.QRect(170, 30, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_tb6600_move_cw.setFont(font)
        self.pb_tb6600_move_cw.setCheckable(True)
        self.pb_tb6600_move_cw.setObjectName("pb_tb6600_move_cw")
        self.pb_tb6600_move_ccw = QtWidgets.QPushButton(self.TB6600)
        self.pb_tb6600_move_ccw.setGeometry(QtCore.QRect(250, 30, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_tb6600_move_ccw.setFont(font)
        self.pb_tb6600_move_ccw.setCheckable(True)
        self.pb_tb6600_move_ccw.setObjectName("pb_tb6600_move_ccw")
        self.bar_tb6600_steps = QtWidgets.QScrollBar(self.TB6600)
        self.bar_tb6600_steps.setGeometry(QtCore.QRect(340, 40, 201, 31))
        self.bar_tb6600_steps.setMaximum(64000)
        self.bar_tb6600_steps.setOrientation(QtCore.Qt.Horizontal)
        self.bar_tb6600_steps.setObjectName("bar_tb6600_steps")
        self.lcd_tb6600_steps = QtWidgets.QLCDNumber(self.TB6600)
        self.lcd_tb6600_steps.setGeometry(QtCore.QRect(410, 70, 64, 31))
        self.lcd_tb6600_steps.setObjectName("lcd_tb6600_steps")
        self.I2CSensors = QtWidgets.QGroupBox(Controller)
        self.I2CSensors.setGeometry(QtCore.QRect(10, 510, 571, 80))
        self.I2CSensors.setObjectName("I2CSensors")
        self.led_0 = QtWidgets.QPushButton(self.I2CSensors)
        self.led_0.setEnabled(True)
        self.led_0.setGeometry(QtCore.QRect(10, 30, 25, 25))
        self.led_0.setStyleSheet("#led_0{\n"
"border-radius:12px}\n"
"\n"
"#led_0:enabled{\n"
"background :green}\n"
"\n"
"\n"
"#led_0:!enabled{\n"
"background :red}")
        self.led_0.setText("")
        self.led_0.setObjectName("led_0")
        self.lcd_0 = QtWidgets.QLCDNumber(self.I2CSensors)
        self.lcd_0.setGeometry(QtCore.QRect(50, 30, 64, 23))
        self.lcd_0.setObjectName("lcd_0")
        self.heartbeat = QtWidgets.QPushButton(Controller)
        self.heartbeat.setEnabled(False)
        self.heartbeat.setGeometry(QtCore.QRect(560, 670, 10, 10))
        self.heartbeat.setAutoFillBackground(False)
        self.heartbeat.setStyleSheet("\n"
"#heartbeat {\n"
"border-radius:2px}\n"
"\n"
"#heartbeat:enabled {\n"
"background :yellow}\n"
"\n"
"#heartbeat:!enabled {\n"
"background: orange}\n"
"\n"
"")
        self.heartbeat.setText("")
        self.heartbeat.setCheckable(False)
        self.heartbeat.setChecked(False)
        self.heartbeat.setFlat(False)
        self.heartbeat.setObjectName("heartbeat")

        self.retranslateUi(Controller)
        self.bar_tb6600_steps.valueChanged['int'].connect(self.lcd_tb6600_steps.display)
        QtCore.QMetaObject.connectSlotsByName(Controller)

    def retranslateUi(self, Controller):
        _translate = QtCore.QCoreApplication.translate
        Controller.setWindowTitle(_translate("Controller", "pi-plates controller"))
        self.PiPlatesRelays.setTitle(_translate("Controller", "Pi-Plates Relays"))
        self.pb_relay_8.setText(_translate("Controller", "Relay 8"))
        self.pb_relay_7.setText(_translate("Controller", "Relay 7"))
        self.pb_relay_13.setText(_translate("Controller", "Relay 13"))
        self.pb_relay_6.setText(_translate("Controller", "Relay 6"))
        self.pb_relay_9.setText(_translate("Controller", "Relay 9"))
        self.pb_relay_5.setText(_translate("Controller", "Relay 5"))
        self.pb_relay_12.setText(_translate("Controller", "Relay 12"))
        self.pb_relay_1.setText(_translate("Controller", "Relay 1"))
        self.pb_relay_14.setText(_translate("Controller", "Relay 14"))
        self.pb_relay_2.setText(_translate("Controller", "Relay 2"))
        self.pb_relay_4.setText(_translate("Controller", "Relay 4"))
        self.pb_relay_11.setText(_translate("Controller", "Relay 11"))
        self.pb_relay_3.setText(_translate("Controller", "Relay 3"))
        self.pb_relay_10.setText(_translate("Controller", "Relay 10"))
        self.PiPlatesGlobal.setTitle(_translate("Controller", "Pi-Plates global"))
        self.pb_relay_all_on.setText(_translate("Controller", "All ON"))
        self.pb_relay_all_off.setText(_translate("Controller", "All OFF"))
        self.TB6600.setTitle(_translate("Controller", "TB6600"))
        self.pb_tb6600_test.setText(_translate("Controller", "Test"))
        self.pb_tb6600_move_cw.setText(_translate("Controller", "CW"))
        self.pb_tb6600_move_ccw.setText(_translate("Controller", "CCW"))
        self.I2CSensors.setTitle(_translate("Controller", "i2c sensors"))
        self.led_0.setToolTip(_translate("Controller", "input green =on, red=off"))
        self.heartbeat.setToolTip(_translate("Controller", "heartbeat"))

